version: "3.9"
services:
  colmap:
    build: 
      context: ./
      dockerfile: docker/Dockerfile-colmap
  neuralangelo:
    build:
      context: ./
      dockerfile: docker/Dockerfile-neuralangelo
  complete-pipeline:
    build:
      context: ./
      dockerfile: docker/Dockerfile.unified 
      args:
        SEQ: Barn.mp4
        SCENE_TYPE: outside